# fly.toml app configuration file generated for fullstack23cicd-ownproject on 2023-12-11T20:16:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstack23cicd-ownproject"
primary_region = "arn"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 3001
  protocol = "tcp"

[[services.ports]]
  handlers = ["http"]
  port = 3001

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
