name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Check commit message for skip
        id: check_skip
        run: echo "::set-output name=skip::$(if [[ $(git log --format=%B -n 1 $GITHUB_SHA) == *"#skip"* ]]; then echo true; else echo false; fi)"
      - name: Deploy only on main branch
        if: ${{ steps.check_skip.outputs.skip != 'true' }}
        run: |
          if [ "${{ github.event_name }}" == "push" ] && [ -z "${{ github.event.pull_request }}" ]; then
            flyctl deploy --remote-only
          else
            echo "Skipping deployment for pull requests or non-push events."
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
            severity: info
            details: Test Succeeded!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: Test Failed!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
            severity: warn
            details: Test Cancelled!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Check commit message for skip
        id: check_skip
        run: echo "::set-output name=skip::$(if [[ $(git log --format=%B -n 1 $GITHUB_SHA) == *"#skip"* ]]; then echo true; else echo false; fi)"
      - name: Bump version and push tag
        if: ${{ steps.check_skip.outputs.skip != 'true' }}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DEFAULT_BRANCH: main
  
  #added secrets to github, modified github settings for permissions